# === 🧠 Stored Execution Rules ===
# - Run on every push and pull request
# - Use latest stable Python
# - Install dependencies via requirements.txt
# - Run tests from /tests/ folder using pytest

name: QuantTroll CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest tests/
